name: bouncy_shot_game
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'
dependencies:
  flame: ^1.10.0
  flame_audio: ^2.1.2
  flame_forge2d: ^0.15.1
  flame_noise: ^0.1.1+7
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.1.1
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/audio/